# Generated by Django 4.2.11 on 2024-06-14 07:40

from django.db import migrations, models
import wasteschedules.models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteschedules', '0002_alter_schedule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[wasteschedules.models.SlugifiableValidator()]),
        ),
    ]
