# Generated by Django 4.2.11 on 2024-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteschedules', '0002_subscription_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
