# Generated by Django 4.2.11 on 2024-05-22 08:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteschedules', '0005_postalcode_delete_location_alter_schedule_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
