# Generated by Django 4.2.11 on 2024-05-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wasteschedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('js_event_id', models.CharField(max_length=255)),
                ('kind', models.IntegerField(choices=[(0, 'Restmüll'), (1, 'Biomüll'), (2, 'Papiermüll'), (4, 'Gelbe Tonne')], default=0)),
                ('date', models.DateField()),
                ('recurring_type', models.IntegerField(choices=[(0, 'not recurring'), (1, 'weekly'), (2, 'every other week'), (3, 'every third week'), (4, 'every fourth week')], default=0, null=True)),
                ('separation_count', models.IntegerField(default=1, null=True)),
                ('rrule_start', models.DateField(null=True)),
                ('until', models.DateField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wasteschedules.schedule')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField()),
                ('new_date', models.DateField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='schedulebuilder.event')),
            ],
            options={
                'ordering': ['old_date'],
            },
        ),
    ]
