# Generated by Django 4.2.11 on 2024-04-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wasteschedules', '0002_subscription_like_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(0, 'Restmüll'), (1, 'Biomüll'), (2, 'Papiermüll'), (4, 'Gelbe Tonne')], default=0)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_type', models.IntegerField(choices=[(0, 'weekly'), (2, 'monthly')], default=0)),
                ('separation_count', models.IntegerField(default=1)),
                ('max_number_of_occurrences', models.IntegerField(default=12)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wasteschedules.schedule')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField()),
                ('new_date', models.DateField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='schedulebuilder.event')),
            ],
            options={
                'ordering': ['old_date'],
            },
        ),
    ]
