# Generated by Django 4.2.11 on 2024-04-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_number_of_occurrences',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurring_type',
            field=models.IntegerField(blank=True, choices=[(0, 'weekly'), (2, 'monthly')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='separation_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
