# Generated by Django 4.2.11 on 2024-06-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exception',
            new_name='EventException',
        ),
    ]
