# Generated by Django 4.2.11 on 2024-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0002_alter_event_max_number_of_occurrences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_number_of_occurrences',
        ),
        migrations.AddField(
            model_name='event',
            name='rrule_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='until',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurring_type',
            field=models.IntegerField(choices=[(0, 'weekly'), (2, 'monthly')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='separation_count',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
