# Generated by Django 4.2.11 on 2024-04-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0003_remove_event_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='js_event_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
