# Generated by Django 4.2.11 on 2024-04-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0004_event_js_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurring_type',
            field=models.IntegerField(choices=[(1, 'weekly'), (2, 'every other week'), (3, 'every third week'), (4, 'every fourth week')], default=0, null=True),
        ),
    ]
