# Generated by Django 4.2.11 on 2024-04-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0005_alter_event_recurring_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurring_type',
            field=models.IntegerField(choices=[(0, 'not recurring'), (1, 'weekly'), (2, 'every other week'), (3, 'every third week'), (4, 'every fourth week')], default=0, null=True),
        ),
    ]
